steps:
  install:
    image: danlynn/ember-cli:3.20.0
    commands:
      - npm install
  lint-js:
    image: danlynn/ember-cli:3.20.0
    commands:
      - npm run lint:js
  lint-hbs:
    image: danlynn/ember-cli:3.20.0
    commands:
      - npm run lint:hbs
  lint-dependencies:
    image: danlynn/ember-cli:3.20.0
    failure: ignore
    commands:
      - ember dependency-lint
  test:
    image: danlynn/ember-cli:3.20.0
    failure: ignore
    commands:
      - npm run test:ember
